version: '3.8'

volumes:
  prometheus:
    name: prometheus
  alertmanager:
    name: alertmanager
  grafana:
    name: grafana

networks:
  prom-graf:
    name: prom-graf
  inception:
    external: true

services:
  # prometheus
  prometheus:
    image: prometheus
    build: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
      - "9093:9093"
    hostname: localhost
    env_file:
      - .env
    volumes:
      - prometheus:/var/lib/prometheus
      - alertmanager:/var/lib/alertmanager
    networks:
      - prom-graf
      - inception
    restart: always

  # grafana
  grafana:
    image: grafana
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - prom-graf 
      - inception
    restart: always

  # mysqld exporter for MariaDB
  mysqld_exporter:
    image: mysqld-exporter
    build:
      dockerfile: ./exporters/Dockerfile.mysqld
    container_name: mysqld-exporter
    command:
      - --config.my-cnf=/etc/.my.cnf
      - --mysqld.address=mariadb:3306
    volumes:
      - ./.my.cnf:/etc/.my.cnf
    networks:
      - inception
      - prom-graf
    restart: always
    ports:
      - "9104:9104"

  # nginx exporter for Nginx
  nginx_exporter:
    image: nginx-exporter
    build:
      dockerfile: ./exporters/Dockerfile.nginx
    container_name: nginx-exporter
    command: -nginx.scrape-uri https://nginx:443/nginx_status
    networks:
      - inception
      - prom-graf
    restart: always
    ports:
      - "9113:9113"

  # php-fpm exporter for WordPress
  php_fpm_exporter:
    image: php-fpm-exporter
    build:
      dockerfile: ./exporters/Dockerfile.php-fpm
    container_name: php-fpm-exporter
    environment:
      FPM_SCRAPE_URI: tcp://wordpress:9000/status
    networks:
      - inception
      - prom-graf
    restart: always
    ports:
      - "9253:9253"
  
  # node exporter for the host machine
  node-exporter:
    image: node-exporter
    build:
      dockerfile: ./exporters/Dockerfile.node
    container_name: node-exporter
    networks:
      - prom-graf
      - inception
    restart: always